controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

contact_success:
    path: /contact/success
    controller: App\Controller\ContactController::contactSuccess



